### ISSUE TITLE
Binary packages are broken

### ISSUE THREAD

**Issue by iliapolo** [iliapolo/pyci#34]
Apparently running almost every operation using the binary release simply fails:

For example:

```bash
/Users/elipolonsky/py-ci-x86_64-Darwin --debug pack --path /Users/elipolonsky/dev/src/github.com/iliapolo/pyci wheel                                                                              [02:15:31]

    ___    _  _    ___     ___
   | _ \  | || |  / __|   |_ _|
   |  _/   \_, | | (__     | |
  _|_|_   _|__/   \___|   |___|
_| """ |_| """"|_|"""""|_|"""""|
"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'

2019-06-06 02:15:32,792 - pyci - INFO - Packaging wheel...

2019-06-06 02:15:32,794 - pyci.api.packager - DEBUG - Running bdist_wheel... [universal=False, repo=None, sha=None, path=/Users/elipolonsky/dev/src/github.com/iliapolo/pyci]
2019-06-06 02:15:32,795 - pyci.api.runner - DEBUG - Running command... [command=/var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/_MEIQguzjz/bin/python setup.py bdist_wheel --bdist-dir /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/tmp92wm5mft/bdist --dist-dir /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/tmp92wm5mft/dist, host=localhost]
2019-06-06 02:15:43,283 - pyci.api.runner - DEBUG - Finished running command. [command=/var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/_MEIQguzjz/bin/python setup.py bdist_wheel --bdist-dir /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/tmp92wm5mft/bdist --dist-dir /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/tmp92wm5mft/dist, exit_code=-6, host=localhost]
2019-06-06 02:15:43,284 - pyci - INFO -

2019-06-06 02:15:43,285 - pyci - DEBUG - Traceback (most recent call last):
  File "pyci/shell/__init__.py", line 37, in wrapper
  File "pyci/shell/subcommands/pack.py", line 116, in wheel
  File "pyci/shell/subcommands/pack.py", line 133, in wheel_internal
  File "pyci/api/packager.py", line 221, in wheel
  File "pyci/api/runner.py", line 106, in run
pyci.api.exceptions.CommandExecutionException: Command '/var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/_MEIQguzjz/bin/python setup.py bdist_wheel --bdist-dir /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/tmp92wm5mft/bdist --dist-dir /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/tmp92wm5mft/dist' executed with an error.
code: -6
error: dyld: Library not loaded: /Users/travis/.travis-pyenv/versions/3.6.4/lib/libpython3.6m.dylib
  Referenced from: /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/_MEIQguzjz/bin/python
  Reason: image not found
output: None


2019-06-06 02:15:43,285 - pyci - ERROR - Command '/var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/_MEIQguzjz/bin/python setup.py bdist_wheel --bdist-dir /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/tmp92wm5mft/bdist --dist-dir /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/tmp92wm5mft/dist' executed with an error.
code: -6
error: dyld: Library not loaded: /Users/travis/.travis-pyenv/versions/3.6.4/lib/libpython3.6m.dylib
  Referenced from: /var/folders/bf/nztm43714sj0fc5_40qgtbx00000gn/T/_MEIQguzjz/bin/python
  Reason: image not found
```

It looks like the python scripts inside the binary package reference paths and libraries that only exist on the machine that built the binary.

**Comment by iliapolo** [comment]
This issue is part of release [0.5.1](https://github.com/iliapolo/pyci/releases/tag/0.5.1)
